# Write your MySQL query statement below

SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID WHERE (E.SALARY, E.DEPARTMENTID) IN  (SELECT MAX(SALARY),DEPARTMENTID FROM EMPLOYEE GROUP BY DEPARTMENTID)